name: Deploy MongoDB App to AKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Kubernetes context
        uses: azure/aks-set-context@v3
        with:
          resource-group: wiz-exercise-rg
          cluster-name: wiz-aks-cluster

      - name: Deploy mongo-secret
        run: kubectl apply -f mongo-secret.yaml

      - name: Deploy mongo-app
        run: kubectl apply -f mongo-app.yaml
